#Theoretical Questions:-
###1.  Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?
ANS:- NumPy stands for “Numerical Python” and it is the standard Python library used for working with arrays (i.e.,vectors & matrices), linear algebra, and other numerical computations. NumPy is written in C, making NumPy arrays faster and more memory efficient than Python lists or arrays.

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation,
sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences:-

(i)NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

(ii)The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

(iii)NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data.Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

(iv)A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.

###2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?
ANS:- In the Numpy library, there are two functions np.mean() and np.average() are present. Both are actually doing nearly the same job of calculating mean/average. The difference comes when we are calculating the weighted average. If that is the case then we have to use np.average(). With np.average function we can calculate both arithmetic mean and weighted average. In this article, we have shown the basic use case of both functions and how they are different from each other.

**np.mean():-** In numpy library, np.mean() is a function used to calculate arithmetic mean of the given array along with the axis.
  
**Code:-** This code calculates the mean (average) of a NumPy array named ‘arr’ and prints both the array and its mean value.

**Example:-**

    import numpy as np
    arr = np.array([1,2,3,4,5,6,7,8,9,10])
    print("Array : ",arr,"\n")
    print("Mean of the Array : ",np.mean(arr))
    
    Output:- Array :  [ 1  2  3  4  5  6  7  8  9 10]
             Mean of the Array :  5.5

**np.average():-** The arithmetic mean and weighted average calculations are more flexible with np.average(). It can calculate the weighted average if we pass the weight; if not, it returns the same value as np.mean(). This implies that the arithmetic mean is the result when we do not pass the weight condition.

**Code:-** This code calculates the mean and weighted average of a NumPy array. The mean is the average of the array’s elements, and the weighted average considers assigned weights for each element in the array.

**Example:-**

    import numpy as np
    arr = np.array([1,2,3,4,5,6,7,8,9,10])
    print("Array : ",arr,"\n")
    print("Mean of the Array : ",np.average(arr),"\n")
    weight = np.array([4,5,6,12,15,10,2,8,19,20])
    print("Weight average of Array : ",np.average(arr, weights=weight))
    
    Output:- Array :  [ 1  2  3  4  5  6  7  8  9 10]
             Mean of the Array :  5.5
             Weight average of Array :  6.574257425742574

In numpy library, both np.mean() and np.average() can be used to calculate arithmetic mean. The differenece comes when we have to perform average on weighted array. np.average() gives us flexibilty to work with the weighted arrays too. If we pass the weight of the array to the function, it can perform weighted average at very ease. That is not the case for the np.mean(). It can only be perfomred on non-weighted arrays.



###3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.
Ans:- **Using the flip() Function:-** The syntax of the numpy.flip() function is as follows:-

**Syntax:-**

    numpy.flip(arr, axis=None)

It is made up of a few parameters:-

    Sr. No.	   Parameter Name	              Parameter Description
     1	          arr	                           input array
     2	          axis	            The default, axis=None, flips all of the  
                                          input array's axes.

The numpy.flip() method in NumPy lets us flip or reverse the contents of an array along an axis. When calling numpy.flip(), indicate the array to be reversed as well as the axis. If we don't provide an axis, NumPy will reverse the contents of our input array along all of its axes.

**Note:-** Because we're dealing with multidimensional arrays, reversing an array may be done in various ways. In a 2d array, reversing may be done both row and column-wise.

The axis input is used to decide whether reversing should be done row or column wise. The orientations along the rows and columns are represented by NumPy axes, like coordinate systems. A NumPy array's beginning axis is axis 0. This axis 0, which runs vertically downward through the rows of NumPy multidimensional arrays, enables column-wise operations. Axis 1 is the second axis of multidimensional NumPy arrays. As a consequence, Axis 1 spans the array columns horizontally. It completes tasks row by row.

**Code:-**

    import numpy as np
    arr = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
    reversed_arr = np.flip(arr)
    print('Reversed Array: ')
    print(reversed_arr)

    Output : Reversed Array:
             [[12 11 10  9]
             [ 8  7  6  5]
             [ 4  3  2  1]]

**Using the reverse() Function:-** The reverse() function is a built-in Python technique that allows us to immediately reverse a list. The reverse() function always returns the sequence's reversed iterator. The biggest disadvantage is that it will function on the original list, which means it will be reversed.

The syntax of the built-in reverse() function is as follows:-

**Syntax:-**

    arr.reverse()

**Code:-**

    import array

    arr=array.array('i',[1,2,6,8,4,2])
    print(arr)
    arr.reverse()
    print("Reversed Array:",arr)

    Output: array('i', [1, 2, 6, 8, 4, 2])
            Reversed Array: array('i', [2, 4, 8, 6, 2, 1])

**Using the flipud() Function:-** The flipud() method will also reverse the Numpy array items. The numpy.flipud() method flips the array (elements in each column) up and down, keeping the shape.

The flipud() method's syntax is as follows:-

**Syntax:-**

    numpy.flipud(array)

**Code:-**

    import numpy as np

    arr= np.array([9, 8, 3, 6, 2, 1])
    result = np.flipud(arr)
    print("Reverse array",(result))
    print("Original array", arr)

    Output:- Reverse array [1 2 6 3 8 9]
             Original array [9 8 3 6 2 1]

In the preceding code, we loaded the NumPy library and then used the method numpy.array() to build a NumPy array. We made a variable and assigned it the method np.flipud(), which took the array we constructed before and displayed the output. The array was shown in reverse order as a result. We also printed the original array to ensure that it either exists or is destroyed by the flipud() function. However, we discovered that flipud() did not affect the original NumPy array.

**Using the fliplr() Function:-** We may quickly reverse an array using the numpy.fliplr() method. The np.fliplr() function flips the array from left to right. The numpy.fliplr() method always takes an array as an argument and returns the same array with a left-right flip. Assuming you have a matrix, a request occurs requiring you to flip the items in each row while keeping the column intact. This function will come in helpful in this circumstance, and it can be accomplished with only one line of code.

**Syntax:-**

    numpy.fliplr(array)

**Code:-**

    import numpy as np
    a=[[1,23],
       [34,6]]
    print(np.fliplr(a))
    print("Orginal array:")
    print(a)

    Output:- [[23  1]
             [ 6 34]]
            Original array:
            [[ 1  23]
             [34   6]]




###4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.
ANS:- NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.Below is a list of all data types in NumPy and the characters used to represent them.

    i - integer
    b - boolean
    u - unsigned integer
    f - float
    c - complex float
    m - timedelta
    M - datetime
    O - object
    S - string
    U - unicode string
    V - fixed chunk of memory for other type ( void )

**Checking the Data Type of an Array:-** The NumPy array object has a property called dtype that returns the data type of the array.

**Example:-**

(i)Get the data type of an array object:-

    import numpy as np
    arr = np.array([1, 2, 3, 4])
    print(arr.dtype)

    Output:- int64

(ii)Get the data type of an array containing strings:-

    import numpy as np
    arr = np.array(['apple', 'banana', 'cherry'])
    print(arr.dtype)

    Output:- <U6

**Creating Arrays With a Defined Data Type:-** We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements.

**Example:-**

(i)Create an array with data type string:-

    import numpy as np

    arr = np.array([1, 2, 3, 4], dtype='S')

    print(arr)
    print(arr.dtype)

    Output:- [b'1' b'2' b'3' b'4']
             |S1

(ii)Create an array with data type 4 bytes integer:-

    import numpy as np

    arr = np.array([1, 2, 3, 4], dtype='i4')

    print(arr)
    print(arr.dtype)

    Output:- [1 2 3 4]
             int32

**Converting Data Type on Existing Arrays:-** The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows us to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or we can use the data type directly like float for float and int for integer.

**Example:-**

(i)Change data type from float to integer by using 'i' as parameter value:-

    import numpy as np

    arr = np.array([1.1, 2.1, 3.1])

    newarr = arr.astype('i')

    print(newarr)
    print(newarr.dtype)

    Output:- [1 2 3]
             int32

(ii)Change data type from float to integer by using int as parameter value:-

    import numpy as np

    arr = np.array([1.1, 2.1, 3.1])

    newarr = arr.astype(int)

    print(newarr)
    print(newarr.dtype)

    Output:- [1 2 3]
             int64

(iii)Change data type from integer to boolean:-

    import numpy as np

    arr = np.array([1, 0, 3])

    newarr = arr.astype(bool)

    print(newarr)
    print(newarr.dtype)

    Output:- [ True False True]
             bool

###5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
ANS:- An ndarray is a (usually fixed-size) multidimensional container of items of the same type and size. The number of dimensions and items in an array is defined by its shape, which is a tuple of N non-negative integers that specify the sizes of each dimension. The type of items in the array is specified by a separate data-type object (dtype), one of which is associated with each ndarray.

As with other container objects in Python, the contents of an ndarray can be accessed and modified by indexing or slicing the array (using, for example, N integers), and via the methods and attributes of the ndarray.

Different ndarrays can share the same data, so that changes made in one ndarray may be visible in another. That is, an ndarray can be a “view” to another ndarray, and the data it is referring to is taken care of by the “base” ndarray. ndarrays can also be views to memory owned by Python strings or objects implementing the memoryview or array interfaces.

There are several differences between ndarrays in NumPy and standard python lists:-

(i)we can append elements to a list, but you can't change the size of a ´numpy.ndarray´ without making a full copy.

(ii)Lists can containt about everything, in numpy arrays all the elements must have the same type.

(iii)In practice, numpy arrays are faster for vectorial functions than mapping functions to lists.

(iv)I think than modification times is not an issue, but iteration over the elements is.

(v)Numpy arrays have many array related methods (´argmin´, ´min´, ´sort´, etc).

I prefer to use numpy arrays when I need to do some mathematical operations (sum, average, array multiplication, etc) and list when I need to iterate in 'items' (strings, files, etc).

###6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
ANS:- NumPy arrays offer significant performance advantages over python lists for large-scale numerical operations.Here's detailed analysis:-

**(i) Homogeneous Data Type:-**

**NumPy arrays:-** Store elements of the same data type (e.g., integers, floats), enabling efficient memory allocation and optimized operations.

**Python lists:-** Can store elements of different data types, requiring additional memory overhead and type checking during operations.

**(ii) Contiguous Memory Allocation:-**

**NumPy arrays:-** Store data in contiguous memory blocks, allowing faster access and manipulation.

**Python lists:-** Store references to objects scattered in memory, leading to slower access and potential memory fragmentation.

**(iii) Vectorized Operations:-**

**NumPy arrays:-** Support vectorized operations, performing computations on entire arrays without explicit loops. This leverages optimized C and Fortran libraries, resulting in significant speedups.

**Python lists:-** Require explicit loops for element-wise operations, introducing interpreter overhead and slowing down computations.

**(iv) Broadcasting:-**

**NumPy arrays:-** Enable broadcasting, allowing operations between arrays of different but compatible shapes. This simplifies code and improves performance.

**Python lists:-** Lack broadcasting capabilities, requiring manual reshaping or looping.

**(v) Optimized Mathematical Functions:-**

**NumPy arrays:-** Provides a rich library of optimized mathematical functions (e.g., np.sin, np.exp, np.dot) implemented in low-level languages, offering superior performance.

**Python lists:-** Rely on built-in functions or custom implementations, which are often slower for large-scale computations.

**Performance Comparison Example:-**

    import numpy as np
    import time

    # Create large lists and arrays
    size = 1000000
    python_list = list(range(size))
    numpy_array = np.arange(size)

    # Measure time for element-wise addition
    start_time = time.time()
    result = [x + 2 for x in python_list]
    print("Python list time:", time.time() - start_time)

    start_time = time.time()
    result = numpy_array + 2
    print("NumPy array time:", time.time() - start_time)

In conclusion, NumPy arrays outperform Python lists in terms of speed and memory efficiency for large-scale numerical operations due to their optimized data storage, vectorized operations, and efficient mathematical functions. If you're working with numerical data in Python, utilizing NumPy is highly recommended for achieving optimal performance.

###7.  Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.
ANS:- In NumPy, vstack and hstack are used to stack arrays vertically and horizontally, respectively. Here's a breakdown of their differences with examples:

**vstack():-**

**Purpose:-** Stacks arrays vertically (row-wise), creating a new array with more rows.

**Syntax:-** np.vstack((array1, array2, ...))

**Example:-**

    import numpy as np

    a = np.array([1, 2, 3])
    b = np.array([4, 5, 6])

    result = np.vstack((a, b))
    print(result)

    Output:-[[1 2 3]
            [4 5 6]]

**hstack():-**

**Purpose:-** Stacks arrays horizontally (column-wise), creating a new array with more columns.

**Syntax:-** np.hstack((array1, array2, ...))

**Example:-**

    import numpy as np

    a = np.array([1, 2, 3])
    b = np.array([4, 5, 6])

    result = np.hstack((a, b))
    print(result)

    Output:- [1 2 3 4 5 6]

**Key differences:-**

**Stacking direction:-** vstack stacks along the first axis (rows), while hstack stacks along the second axis (columns).

**Shape requirements:-** For vstack, all input arrays must have the same number of columns. For hstack, they must have the same number of rows.

###8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.
ANS:- In NumPy, both fliplr() and flipud() are used to reverse the order of elements in an array, but they operate along different axes:

**fliplr():-**

**Function:-** Flips the array horizontally, i.e., reverses the order of elements along the second axis (columns).

**Effect on 2D arrays:-** Reverses the order of columns in each row.

**Effect on higher-dimensional arrays:-** Reverses the order of elements along the second axis, leaving other axes unchanged.

**Equivalent operation:-** np.flip(m, axis=1)



**flipud():-**

**Function:-** Flips the array vertically, i.e., reverses the order of elements along the first axis (rows).

**Effect on 2D arrays:-** Reverses the order of rows.

**Effect on higher-dimensional arrays:-** Reverses the order of elements along the first axis, leaving other axes unchanged.

**Equivalent operation:-** np.flip(m, axis=0)

**Examples:-**

    import numpy as np

    arr = np.array([[1, 2, 3], [4, 5, 6]])

    print("Original array:")
    print(arr)

    print("\nfliplr():")
    print(np.fliplr(arr))

    print("\nflipud():")
    print(np.flipud(arr))

    Output:  Original array:
             [[1 2 3]
             [4 5 6]]

             fliplr():
             [[3 2 1]
             [6 5 4]]

             flipud():
             [[4 5 6]
             [1 2 3]]

**Key points:-**

**Axis:-** fliplr() operates along the second axis (columns), while flipud() operates along the first axis (rows).

**2D arrays:-** fliplr() mirrors the array left-to-right, while flipud() mirrors it top-to-bottom.

**Higher dimensions:-** Both functions only flip elements along the specified axis, leaving other dimensions unchanged.

###9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
ANS:- The array_split() method in NumPy is used to split an array into multiple sub-arrays.

**Functionality:-**

**Splitting into equal parts:-** If the array can be divided evenly into the specified number of sub-arrays, array_split() will do so.

**Handling uneven splits:-** If the array cannot be divided evenly, array_split() will distribute the extra elements across the first few sub-arrays. This means the first few sub-arrays may have one more element than the remaining sub-arrays.

**Example:-**

    import numpy as np

    arr = np.arange(8)  # Create an array [0, 1, 2, 3, 4, 5, 6, 7]

    # Split into 3 sub-arrays
    split_arrays = np.array_split(arr, 3)

    print(split_arrays)

    Output: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7])]

In this example, the array arr cannot be divided evenly into 3 parts. So, array_split() creates 3 sub-arrays:-

(i)The first sub-array has 3 elements.

(ii)The second sub-array also has 3 elements.

(iii)The third sub-array has the remaining 2 elements.

**Difference between array_split() and split():-**

**array_split():-** Allows uneven splits, as demonstrated above.

**split():-** Raises an error if the array cannot be divided evenly.

**Key points:-**

(i)array_split() is a more flexible way to split arrays than split() because it handles uneven splits.

(ii)We can specify the axis along which to split the array using the axis parameter.

(iii)The indices_or_sections parameter can be an integer (to specify the number of sub-arrays) or a list of indices (to specify the split points).


###10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?
ANS:- Vectorization and broadcasting are important concepts in NumPy that enhance the efficiency of array operations in Python.

**Vectorization Concept:-** Vectorization allows us to perform operations on entire arrays at once instead of using loops to iterate through individual elements. This is possible because NumPy's operations are implemented in optimized C code, which makes them much faster than Python loops. For example, if we want to add two arrays together, we can do it directly like this:

    import numpy as np

    # Create two arrays
    a = np.array([1, 2, 3])
    b = np.array([4, 5, 6])

    # Vectorized addition
    result = a + b
    print(result)  
    
    # Output:- [5 7 9]

    In this example, the addition is applied to each corresponding element of a and b without needing to write a loop.

**Broadcasting Concept:-** Broadcasting, on the other hand, allows NumPy to work with arrays of different shapes during arithmetic operations. When you perform operations on arrays of different sizes, NumPy automatically expands the smaller array across the larger one to make their shapes compatible. This means you can easily perform operations without reshaping the arrays manually.

For instance, if we add a scalar to an array, broadcasting handles it seamlessly:-

    # Create an array
    a = np.array([1, 2, 3])

    # Add a scalar
    result = a + 5
    print(result)  
    
    # Output:- [6 7 8]

    Here, the scalar 5 is broadcasted to match the shape of a, allowing for element-wise addition.


**Another example of broadcasting is when adding a 1D array to a 2D array:-**

    # Create a 2D array
    b = np.array([[1, 2, 3],
                 [4, 5, 6]])

    # Create a 1D array
    c = np.array([10, 20, 30])

    # Add the 1D array to the 2D array
    result = b + c
    print(result)

    # Output:- [[11 22 33]
               [14 25 36]]

    In this case, the 1D array c is broadcasted across each row of the 2D array b, enabling element-wise addition.

Both vectorization and broadcasting make array operations in NumPy much more efficient by eliminating the need for explicit loops and enabling operations on arrays of different shapes. This results in cleaner code and faster execution, especially when working with large datasets. Overall, these concepts are fundamental to harnessing the full power of NumPy in data analysis and scientific computing.

#Practical Questions:-
###1.  Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [ ]:
import numpy as np


arr1 = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
transposed_arr = arr1.transpose()
print(transposed_arr)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


###2.  Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.





In [ ]:
import numpy as np

arr_1d = np.arange(1,11)
print("1D Array:")
print(arr_1d)
arr_2_5 = arr_1d.reshape(2,5)
print("\n2*5 Array:")
print(arr_2_5)
arr_5_2 = arr_1d.reshape(5,2)
print("\n5*2 Array:")
print(arr_5_2)

1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

2*5 Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

5*2 Array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


###3.  Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [ ]:
import numpy as np

array = np.random.rand(4,4)
array = np.pad(array,pad_width = 1,mode = 'constant',constant_values = 0)
print(array)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.52058068 0.72953205 0.47640191 0.53332244 0.        ]
 [0.         0.10411815 0.00442961 0.08123721 0.17323934 0.        ]
 [0.         0.87091036 0.27312968 0.68835862 0.41420691 0.        ]
 [0.         0.76579717 0.49714194 0.17509609 0.67965641 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


###4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [ ]:
import numpy as np

array = np.arange(10,61,5)
print(array)

[10 15 20 25 30 35 40 45 50 55 60]


###5.  Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [1]:
import numpy as np

strings = np.array(['python','numpy','pandas'])

uppercase_strings = np.char.upper(strings)
lowercase_strings = np.char.lower(strings)
titlecase_strings = np.char.title(strings)

print("uppercase:", uppercase_strings)
print("lowercase:", lowercase_strings)
print("titlecase:", titlecase_strings)

uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
lowercase: ['python' 'numpy' 'pandas']
titlecase: ['Python' 'Numpy' 'Pandas']


###6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [3]:
import numpy as np

words = ["hello", "world","numpy","array"]
spaced_words = []
for word in words:
   spaced_word = " ".join(word)
   spaced_words.append(spaced_word)
array_of_words = np.array(spaced_words)
print(array_of_words)

['h e l l o' 'w o r l d' 'n u m p y' 'a r r a y']


###7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [4]:
import numpy as np


array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])


addition_result = array1 + array2
print("Addition:\n", addition_result)


subtraction_result = array1 - array2
print("Subtraction:\n", subtraction_result)

multiplication_result = array1 * array2
print("Multiplication:\n", multiplication_result)


division_result = array1 / array2
print("Division:\n", division_result)

Addition:
 [[ 8 10 12]
 [14 16 18]]
Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


###8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [5]:
import numpy as np


identity_matrix = np.eye(5)

diagonal_elements = np.diag(identity_matrix)

print("Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:\n", diagonal_elements)

Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements:
 [1. 1. 1. 1. 1.]


###9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [6]:
import numpy as np

def is_prime(num):
    """Checks if a number is prime."""
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

random_array = np.random.randint(0, 1001, 100)

prime_numbers = []
for num in random_array:
    if is_prime(num):
        prime_numbers.append(num)

print("Prime numbers in the array:", prime_numbers)

Prime numbers in the array: [131, 379, 317, 739, 7, 113, 823, 79, 709, 463]


###10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [9]:
import numpy as np

temperatures = np.random.randint(15, 35, 30)

temperatures_reshaped = temperatures.reshape(5, 6)

weekly_averages = np.mean(temperatures_reshaped, axis=1)

print("Daily Temperatures:")
print(temperatures)

print("\nWeekly Averages:")
print(weekly_averages)

Daily Temperatures:
[30 30 24 17 32 23 33 15 20 15 21 24 22 20 33 31 19 22 34 20 33 27 20 27
 34 17 29 33 17 15]

Weekly Averages:
[26.         21.33333333 24.5        26.83333333 24.16666667]
